#!/bin/sh
# get default sink name, usually it's set as default in pulse config.
SINK0=$(pactl list sinks short | grep 'analog-stereo' | awk '{print $2}')
#SINK0=$(pactl list sinks short | grep 'combined' | awk '{print $2}')
[ -z "$SINK0" ] && SINK0="alsa_output.pci-0000_00_1b.0.analog-stereo"
export SINK0="$SINK0"
