#!/bin/sh
# create nonexistent dirs
# shellcheck disable=SC2174 # -m only applies to the deepest directory

# this check is the simple optimization (force run all if $1 not empty)
if [ ! -d "$CSCRDIR" ] || [ -n "$1" ]; then

mkdir -p "$CSCRDIR"
mkdir -p "$CSCRDIR/rate"
mkdir -p "$XDG_CONFIG_HOME/npm"
mkdir -p "$XDG_DATA_HOME/mpd"
mkdir -p "$XDG_DATA_HOME/python"
mkdir -p "$XDG_DATA_HOME/tor"
mkdir -p "$XDG_DATA_HOME/vim/undo" "$XDG_DATA_HOME/vim/swap" "$XDG_DATA_HOME/vim/backup"
mkdir -p "$XDG_DATA_HOME/wineprefixes"
mkdir -p "$HOME/Downloads/build"
mkdir -p -m 0700 "$HOME/.local/.hid"

fi
