#!/bin/sh
# source terminal colors for global use in my scripts
# example:
# printf "%s\n" "Text in ${RED}red${END}, white and ${BLU}blue${END}."

# foreground colors
END=$(printf "%b" "\033[0m")
RED=$(printf "%b" "\033[1;31m")
GRN=$(printf "%b" "\033[1;32m")
YEL=$(printf "%b" "\033[1;33m")
BLU=$(printf "%b" "\033[1;34m")
MAG=$(printf "%b" "\033[1;35m")
CYN=$(printf "%b" "\033[1;36m")

# use color & swap background and foreground colors
DEF_S=$(printf "%b" "\033[1;7m")
RED_S=$(printf "%b" "\033[1;41m")
GRN_S=$(printf "%b" "\033[1;42m")
YEL_S=$(printf "%b" "\033[1;43m")
BLU_S=$(printf "%b" "\033[1;44m")
MAG_S=$(printf "%b" "\033[1;45m")
CYN_S=$(printf "%b" "\033[1;46m")

# BOLD, ITALIC, UNDERLINE
BLD=$(printf "%b" "\033[1m")
ITQ=$(printf "%b" "\033[3m")
UND=$(printf "%b" "\033[4m")

# FOLLOWING LINES - ONLY EXPORTS
# foreground colors
export END
export RED
export GRN
export YEL
export BLU
export MAG
export CYN

# use color & swap background and foreground colors
export DEF_S
export RED_S
export GRN_S
export YEL_S
export BLU_S
export MAG_S
export CYN_S

# BOLD, ITALIC, UNDERLINE
export BLD
export ITQ
export UND
