#!/bin/sh
# source terminal colors for global use in my scripts

export END=$(printf '\e[0m')
export RED=$(printf '\e[1;31m')
export GRN=$(printf '\e[1;32m')
export YEL=$(printf '\e[1;33m')
export BLU=$(printf '\e[1;34m')
export MAG=$(printf '\e[1;35m')
export CYN=$(printf '\e[1;36m')

export DEF_I=$(printf '\e[1;7m')
export RED_I=$(printf '\e[1;41m')
export GRN_I=$(printf '\e[1;42m')
export YEL_I=$(printf '\e[1;43m')
export BLU_I=$(printf '\e[1;44m')
export MAG_I=$(printf '\e[1;45m')
export CYN_I=$(printf '\e[1;46m')
