#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

#---- COMMON ----#
alias \
    cp="cp -vi" \
    rm="rm -vi" \
    mv="mv -vi" \
    calc="python3 -ic 'from math import *'" \
    nt="$TERMINAL &>/dev/null & disown" \
    lld="sudo du -ah --max-depth 1" \
    lld2="sudo du -ah --max-depth 2" \
    llda="sudo du -ah" \
    psl="ps -ef --forest" \
    psg="ps -ef | head -1; ps -ef | grep" \
    sbrc="$EDITOR /etc/bash.bashrc" \
    sp="$EDITOR ~/.profile" \
    sbh="$EDITOR ~/.bash_history" \
    sxrc="$EDITOR ~/.xinitrc" \
    sxres="$EDITOR ~/.Xresources" \
    sxlog="cat ~/.local/share/xorg/Xorg.0.log | $PAGER" \
    sxrlog="cat /var/log/Xorg.0.log | $PAGER" \
    si3c="$EDITOR ~/.config/i3/config" \
    si3s="$EDITOR ~/.config/py3status/config" \
    svc="$EDITOR ~/.config/nvim/init.vim" \
    scv="$EDITOR ~/.config/cvim/.cvimrc" \
    sqc="$EDITOR ~/.config/qutebrowser/config.py" \
    sali="$EDITOR ~/.config/aliasrc" \
    stodo="$EDITOR ~/Documents/Pomodoro/TODO.txt" \
    sudo="sudo " \
    trm="rm -vf ~/Downloads/torrents/*.torrent" \
    venv="source venv/bin/activate" \
    pp="sudo pacman -S" \
    pd="python -m pydoc" \
    pe="python -me"
    # pe 'module_name' 'edit'/'view'. source:pypi.org/project/e/

# nvim
alias \
        neo="nvim " \
        neoc="nvim +PlugClean +qall" \
        neou="nvim +PlugClean +PlugInstall +PlugUpdate +UpdateRemotePlugins +qall" \
        neous="nvim +PlugClean +PlugInstall +PlugUpdate +UpdateRemotePlugins +qall > /dev/null" \
        magit="nvim -c MagitOnly"

# Colorize commands when possible.
alias \
        grep="grep --color=auto" \
        ls="ls -hN --color=auto --group-directories-first" \
        la="ls -Fa --color=auto" \
        ll="ls -Flas --color=auto" \
        diff="diff --color=auto" \
        ccat="highlight --out-format=ansi"

#---- PIP ----#
alias pip-l="pip3 freeze | $PAGER"
alias pip-s="pip3 freeze | grep -i"
alias pip-r="pip3 uninstall"
alias pip-i="pip3 install --ignore-installed --user --upgrade"
alias pip-u-all="pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1|xargs -n1 pip3 install --user --upgrade"

#----- PIP FOR VENV -----#
alias pip-list="pip freeze | less"
alias pip-search="pip freeze | grep -i"
alias pip-remove="pip uninstall"
alias pip-install="pip install -U"
alias pip-upgrade-all="pip freeze --local | grep -v '^\-e' | cut -d = -f 1|xargs -n1 pip install -U"
alias pip-req="pip freeze > requirements.txt"
