#!/bin/sh
# FUNCTIONS that is work only in interactive mode
# (cannot be used inside .xinitrc for example)

#From the bash(1) man page:
#Aliases are not expanded when the shell is not interactive, unless the
#expand_aliases shell option is set using shopt
#(see the description of shopt under SHELL BUILTIN COMMANDS below).

red=$'\e[1;31m'; grn=$'\e[1;32m'; yel=$'\e[1;33m'; blu=$'\e[1;34m'; mag=$'\e[1;35m'; cyn=$'\e[1;36m'; end=$'\e[0m'

# expand any alias in $1 before the execution
rit()   { eval $1; }
# suppress output of the $1 command
sup()   { "$(rit $1)" >/dev/null 2>&1; }
# fork $1 command to background and don't create nohup.out
nhp()   { nohup "$(rit $1)" >/dev/null 2>&1 & }

# source if file exist
source_if_exist() { [[ -f "$1" ]] && source "$1"; }

# find process with fzf and kill it
k() {
    local pid
    pid=$(ps -ef | sed "/fzf --header-lines=1/d" | fzf --header-lines=1 -e -0 -1 -q "$1" | awk '{print $2}')
    [ -n "$pid" ] && kill -9 "$pid"
}

ls_colored() {
    ls -Flav --color=always | awk '
        BEGIN {
            FPAT = "([[:space:]]*[^[:space:]]+)";
            OFS = "";
        }
        {
            $2 = "'${red}'" $2 "'${end}'";
            $3 = "'${cyn}'" $3 "'${end}'";
            $4 = "'${cyn}'" $4 "'${end}'";
            $5 = "'${red}'" $5 "'${end}'";
            $6 = "'${cyn}'" $6 "'${end}'";
            $7 = "'${cyn}'" $7 "'${end}'";
            $8 = "'${red}'" $8 "'${end}'";
            print
        }
    '
}

. "$XDG_CONFIG_HOME/funcgit"

