#!/bin/sh
# FUNCTIONS that is work only in interactive mode
# (cannot be used inside .xinitrc for example)
# color variables are sourced once in .profile from termcolors script
# shellcheck disable=SC1090 ## can't follow non-constant source.
# shellcheck disable=SC2086 ## Double quote to prevent globbing and word splitting.

#From the bash(1) man page:
#Aliases are not expanded when the shell is not interactive, unless the
#expand_aliases shell option is set using shopt
#(see the description of shopt under SHELL BUILTIN COMMANDS below).

# expand any alias in $1 before the execution
rit()   { eval $1; }
# suppress output of the $1 command
sup()   { "$(rit $1)" >/dev/null 2>&1; }
# fork $1 command to background and don't create nohup.out
nhp()   { nohup "$(rit $1)" >/dev/null 2>&1 & }

sie() { [ -f "$1" ] && . "$1"; } # source if file exist
sip() { hash "$1"   && . "$1"; } # source if found at $PATH

sage() { eval "$(ssh-agent)"; }

k() { # find process with fzf and kill it
    pid=$(ps -ef | sed "/fzf --header-lines=1/d" | fzf --header-lines=1 -e -0 -1 -q "$1" | awk '{print $2}')
    [ -n "$pid" ] && kill -9 "$pid"
}

# shellcheck disable=SC2012 ## Use find instead
ls_colored() {
    ls -Flav "$@" | head -n 1
    ls -Flav --color=always "$@" | sed 1d | awk '
        BEGIN {
            FPAT = "([[:space:]]*[^[:space:]]+)";
            OFS = "";
        }
        {
            $2 = "'"${RED}"'" $2 "'"${END}"'";
            $3 = "'"${CYN}"'" $3 "'"${END}"'";
            $4 = "'"${CYN}"'" $4 "'"${END}"'";
            $5 = "'"${RED}"'" $5 "'"${END}"'";
            $6 = "'"${CYN}"'" $6 "'"${END}"'";
            $7 = "'"${CYN}"'" $7 "'"${END}"'";
            $8 = "'"${RED}"'" $8 "'"${END}"'";
            print
        }
    ' | awk '
        BEGIN {
            FPAT = ".";
            OFS = "";
        }
        {
            $2 = "'"${CYN}"'" $2 "'"${END}"'";
            $4 = "'"${RED}"'" $4 "'"${END}"'";
            $5 = "'"${CYN}"'" $5 "'"${END}"'";
            $7 = "'"${RED}"'" $7 "'"${END}"'";
            $8 = "'"${CYN}"'" $8 "'"${END}"'";
            $10 = "'"${RED}"'" $10 "'"${END}"'";
            print
        }
    '
}

. "$XDG_CONFIG_HOME/funcgit"

