#!/bin/sh
# MAIN

export BROWSER="firefox-developer-edition"
export EDITOR="nvim"
export MANPAGER="nvim +Man!"
export PAGER="page -w -q 90000 -e 'call timer_start(500, { -> cursor(1,1) })'"
export TERMINAL="st"

export WNDX_SOURCES="$HOME/source"
export WNDX_SCRIPTS="$WNDX_SOURCES/scripts-wndx"
export CSCRDIR="$XDG_CACHE_HOME/cscripts"
export SUDO_ASKPASS="$WNDX_SCRIPTS/sh/dmenu/dmenu_askpass"
export S2D=1
export VHI="$XDG_CONFIG_HOME/nvim/conf/hi.vim"
export POMODORO_DIR="$HOME/Documents/Pomodoro"

export CMAKE_EXPORT_COMPILE_COMMANDS=1
export CTEST_OUTPUT_ON_FAILURE=1

# export CC=/usr/bin/clang CXX=/usr/bin/clang++
# export CC=/usr/bin/gcc   CXX=/usr/bin/g++
# export CC=clang CXX=clang++
export CC=gcc   CXX=g++
