#!/bin/sh
# less/man colors

export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '\E[1;31m')";     a="${a%_}"
export LESS_TERMCAP_md="$(printf '%b' '\E[1;36m')";     a="${a%_}"
export LESS_TERMCAP_me="$(printf '%b' '\E[0m')";        a="${a%_}"
export LESS_TERMCAP_so="$(printf '%b' '\E[01;44;33m')"; a="${a%_}"
export LESS_TERMCAP_se="$(printf '%b' '\E[0m')";        a="${a%_}"
export LESS_TERMCAP_us="$(printf '%b' '\E[1;32m')";     a="${a%_}"
export LESS_TERMCAP_ue="$(printf '%b' '\E[0m')";        a="${a%_}"

