#!/bin/sh
# less/man colors
# shellcheck disable=SC2155 # Declare and assign separately to avoid masking return values.

export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '\033[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '\033[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '\033[0m')"
export LESS_TERMCAP_so="$(printf '%b' '\033[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '\033[0m')"
export LESS_TERMCAP_us="$(printf '%b' '\033[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '\033[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
