#!/bin/sh
## populate PATH with additional dirs to look for the executables

## PATH variable before the modification by this file
[ -z "$PATH0" ] && export PATH0="$PATH"
## to be able to re-source this file after modification
## without adding duplicates from the previous PATH env.
PATH="$PATH0"

PATH="${PATH}:$WNDX_SCRIPTS/.pth/bin"
PATH="${PATH}:$WNDX_SCRIPTS/.pth/sbin"
PATH="${PATH}:$WNDX_SCRIPTS/.pth/msym"
PATH="${PATH}:$WNDX_SCRIPTS/.pth/lnch"

PATH="${PATH}:$HOME/.local/bin"
PATH="${PATH}:$CARGO_HOME/bin"
PATH="${PATH}:$XDG_DATA_HOME/npm/bin"


export PATH
