#!/bin/sh
# PATH envs

export PATH="${PATH}:$HOME/.local/bin"
export PATH="${PATH}:$CARGO_HOME/bin"

# add to $PATH scripts and subdirs (excluding .* , _* dirs)
export PATH="$PATH:$(find "$SCRIPTS" -type d ! -path "*/.*" ! -path "*/_*" -printf "%p:")"
