#!/bin/sh
# PATH envs

export PATH="${PATH}:$HOME/.local/bin"
export PATH="${PATH}:$CARGO_HOME/bin"
export PATH="${PATH}:${XDG_DATA_HOME}/npm/bin"

# add to $PATH scripts and subdirs (excluding .* , _* dirs)
spaths="$(find "$SCRIPTS" -type d ! -path "*/.*" ! -path "*/_*" -printf "%p:")"
export PATH="$PATH:$spaths"
