#!/bin/sh
# env var core file
export ENVDIR="$HOME/.config/env"
export ENVSCR="$ENVDIR/scripts"
#/////////////////////////////////////////////////////////////////
#//////______////____////__////__//______//////______//________///
#///__////////__////__//__////__//__////__//__////////__//////////
#////____////__////__//__////__//______////__////////______///////
#///////__//__////__//__////__//__////__//__////////__////////////
#______//////____//////____////__////__////______//________///////
#/////////////////////////////////////////////////////////////////

source "$ENVDIR/cleanup"
source "$ENVDIR/main"
source "$ENVDIR/manless"
source "$ENVDIR/path"

source "$ENVSCR/mkdir_nonexistent"
source "$ENVSCR/get_analog-stereo_sink"
source "$ENVSCR/get_dflt_sink"
source "$ENVSCR/get_hdmi_sink"

for f in $ENVDIR/.hid/*; do source $f; done; unset -v f

