#!/bin/sh
# env var core file

# shellcheck disable=SC1090 ## can't follow non-constant source.
# shellcheck disable=SC1091 ## Not following (No such file or directory)
export ENVDIR="$HOME/.config/env"
export ENVSCR="$ENVDIR/scripts"

. "$ENVDIR/cleanup"
. "$ENVDIR/main"
. "$ENVDIR/manless"
. "$ENVDIR/path"

. "$ENVSCR/mkdir_nonexistent"
. "$ENVSCR/get_analog-stereo_sink"
. "$ENVSCR/get_dflt_sink"
. "$ENVSCR/get_hdmi_sink"
. "$ENVSCR/termcolors"
. "$ENVSCR/fzf_default_command"

[ -d "$ENVDIR/.hid/" ] && for f in "$ENVDIR/.hid/"*; do . "$f"; done; unset -v f

